Sum
js-tasks-ru/vue-20230120_volnuistrelok pull request #2
Opened 2023-02-01 11:42 UTC by volnuistrelok

function sum

2023-02-01 18:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-01 18:29 UTC, ShGKme reviewed
Задача sum принята, но PR будет принят, когда будут решены все добавленные задачи.

2023-02-03 14:52 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-05 17:15 UTC, volnuistrelok commented
calc

2023-02-05 21:17 UTC, ShGKme requested changes
В `01-basics/02-VueCalculator` вычисляемое свойство имеет побочный эффект...

2023-02-05 21:17 UTC, ShGKme commented on 01-basics/01-CounterButtonApp/index.html
>      </div>
У текстовой интерполяции обычно принято добавлять пробелы в скобках: `{{ counter }}`

2023-02-05 21:17 UTC, ShGKme commented on 01-basics/01-CounterButtonApp/index.html
>      </div>
Директивы чаще используют в сокращённом варианте `@click="counter++"`

2023-02-05 21:17 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +    }
Вычисляемое свойство ни в коем случае не должно иметь побочных эффектов в процессе вычисления. Это вычисляемое свойство во время вычисления меняет состояние компонента через`this.oper`.

Если переменная `oper` нужна только во время вычисления `calculatingResults`, у неё только там определяется значение и там же используется - то это должна быть обычная переменная. Не реактивные данные компонента.

2023-02-08 22:11 UTC, ShGKme requested changes
Осталась старая проблема с побочным эффектом в вычисляемом свойстве.

2023-02-08 22:11 UTC, ShGKme commented on 01-basics/01-CounterButtonApp/index.html
> +      <button type="button" @:click="counter++">{{ counter }}</button>
Записи `@:event` во Vue нет. В короткой форме привязка события заменяется с двоеточием `@click`.

2023-02-08 22:11 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +            return eval(this.input_one + this.oper + this.input_two)
Добавилась переменная `oper`, но она не используется. Вычисляемое свойство всё ещё при вычислении меняет свойство экземпляра `this.oper`, хотя это свойство теперь и не является реактивными данными компонента.

2023-02-08 22:12 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-09 21:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-02-09 21:27 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-02-09 21:27 UTC, merged